import { useLocale, type Lang } from './locale'

const ui = {
  de: {
    writeMe: 'Schreib Mir',
    firstTalk: 'Erstgespräch',
    systemStart: 'System Start',
    details: 'Details',
    detailsArrow: 'Details →',
    detailsView: 'Details ansehen →',
    whatsapp: 'WhatsApp',
    moreAbout: 'Mehr über Michél',
    openPillar: 'Säule öffnen →',
    openPillarBtn: 'Säule öffnen',
    checkStart: 'Unverbindlich prüfen',
    prevOffer: 'Vorheriges Angebot',
    nextOffer: 'Nächstes Angebot',
    startFocus: 'Startschwerpunkt:',
    theme: 'Farbschema',
    day: 'Tag',
    night: 'Nacht',
    system: 'System',
    footerLine: 'Leistung beginnt mit Gesundheit.',
    footerAbout:
      'M³ vereint Stoffwechsel (M¹), Biomechanik (M²) und Mindset (M³) zu einem alltagstauglichen System.',
    footerModules: 'Module',
    footerContact: 'Kontakt',
    footerWaTalk: 'WhatsApp Erstgespräch',
    footerWaCat: 'WhatsApp Katalog',
    footerAboutMichel: 'Über Michél',
    footerCopy: '© 2026 Michél Meier · M³ Performance & Gesundheit',
    imprint: 'Impressum',
    privacy: 'Datenschutz',
    painfree: 'Schmerzfrei',
    sitemap: 'Sitemap',
    footerMental: 'M³ Mental',
    problemAlt: 'Michél bei der Arbeit in den M³ Angeboten',
    h1a: 'Leistung',
    h1b: 'beginnt mit',
    h1c: 'Gesundheit.',
    heroPitch:
      'Härteres Training nützt nichts, wenn das Fundament brennt. Hier geht es um Stoffwechsel, Bewegung und Routinen — in der richtigen Reihenfolge, mit Michél.',
    startEyebrow: 'M³ System Start',
    startH: 'Nicht irgendein Angebot. Deine Eingangstür.',
    startLead:
      'Der System Start ordnet dich in dieses System ein. Du musst die Säule nicht vorher kennen.',
    moreLearn: 'Mehr erfahren',
    lessLearn: 'Weniger',
    compassH: 'System-Kompass',
    compassP: 'Wo spürst du aktuell deine größte Hürde?',
    frameworkEyebrow: 'M³ System',
    frameworkH: 'So arbeitet Michél.',
    frameworkLead: 'Drei Säulen. Feste Reihenfolge. Kein Angebotskatalog.',
    pillarsEyebrow: 'Drei Säulen. Ein System.',
    pillarsH: 'Gesundheit ist kein isolierter Muskel.',
    pillarsLead: 'Stoffwechsel, Bewegung und mentale Routinen bedingen einander.',
    modulesEyebrow: 'Angebote nach Säule',
    modulesH: 'Deine Möglichkeiten mit M³',
    modulesLead:
      'Zuerst M¹ Metabolism, dann M² Movement. M³ Mental begleitet beides — kein separates Einzelangebot.',
    modulesM3Note:
      'M³ ist die schließende Säule: Schlaf, Stress und Routinen — damit du am Ende der begleiteten Phase selbstverantwortlich weitergehst. Kein Extra-Angebot. Der Halt, wenn Michél nicht mehr neben dir steht.',
    modulesM3Cta: 'Zur Säule M³',
    back: 'Zurück',
    backHome: 'Zur Startseite',
    michelEyebrow: 'Authentizität',
    michelH: 'Hinter M³ steckt mehr als Training.',
    michelLead:
      'Michél ist kein Trainer, der ein System von der Stange verkauft. Er kommt aus 30+ Jahren Bewegung & Erfahrung: Breakdance, Bühne, Weltmeisterschaft — und aus dem Leben dazwischen. Alleinerziehender Vater. Ein Bandscheibenvorfall im Halswirbelbereich, der ihn fast gestoppt hätte. Jahre, in denen Disziplin allein nicht mehr gereicht hat.',
    michelLead2:
      'Genau deshalb sitzt M³. Er kennt den Moment, in dem der Körper nicht mitzieht, obwohl der Kopf will. Und er kennt den anderen: wenn jemand Verständnis braucht — und wann einen klaren Impuls. Ohne Dogma. Ohne Show. Mit dem Ziel, dass du irgendwann ohne ihn weiterkommst.',
    michelQuote: 'Manchmal braucht es Verständnis. Manchmal einen Arschtritt. Oft beides.',
    michelMeta: '2006 / 2007 · IDO World Champion · Master Personal Trainer i. A. · 30+ Jahre Bewegung',
    faqEyebrow: 'Klarheit vorab',
    faqH: 'Häufige Fragen',
    ctaBefore: 'Bereit, deine ',
    ctaGold: 'Gesundheit',
    ctaAfter: ' neu zu strukturieren?',
    ctaLead: 'Veränderung beginnt mit einer Entscheidung. 20 Minuten Orientierung – direkt mit Michél.',
    ctaTalk: 'Kostenloses Erstgespräch',
    ctaMoreStart: 'Mehr über den System Start',
    forWhom: 'Für wen',
    forWhomH: 'Wenn das hier sitzt, sitzt das Modul.',
    includes: 'Enthalten',
    includesH: 'Was wir konkret machen.',
    audienceEyebrow: 'Für wen M³ ist',
    audienceH: 'Echte Resultate für echte Menschen',
    audienceLead:
      'Keine Wunderpillen, keine 14-Tage-Crash-Diäten. Wir begleiten dich, bis du deinen Körper selbstständig steuerst.',
    processEyebrow: 'Ablauf',
    processH: 'So arbeiten wir zusammen',
    preferStart: 'Lieber mit System Start',
    context: 'Einordnung',
    partOf: 'Teil von',
    more: 'Weiter',
    related: 'Passende Module',
    scienceEyebrow: 'Grundlage',
    scienceH: 'Was wir zugrunde legen.',
    experienceEyebrow: 'Erfahrung',
    principlesEyebrow: 'Arbeitsweise',
    principlesH: 'So setzen wir das um.',
    signalsEyebrow: 'Einordnung',
    signalsH: 'Wann diese Säule zuerst kommt.',
    pillarCtaLead: '20 Minuten. Einordnung, Priorität, nächster Schritt.',
    noModules: 'M³ ist der Halt des Systems — kein separates Angebot. Der Einstieg läuft über den System Start.',
    aboutPortrait: 'Michél Meier – Gründer & Personal Trainer',
    aboutYears: '30+ Jahre Bewegung & Performance',
    aboutValues: 'Werte & Haltung',
    ssEyebrow: 'M³ System Start',
    ssH: 'Nicht irgendein Angebot. Deine Eingangstür.',
    ssLead:
      'Der System Start ordnet dich in dieses System ein. Du musst die Säule nicht vorher kennen.',
    ssWhy: 'Warum das stimmt.',
    ssP1:
      'Viele wollen etwas verändern und wissen nicht, wo sie beginnen sollen. Brauchst du Ernährung, Stoffwechsel, Bewegung – oder eine Kombination?',
    ssP2: 'Genau das beantwortet der System Start: Status quo, Prioritäten, klarer nächster Schritt.',
    ssCompass: 'Wo ist deine größte Hürde?',
    ssYourStart: 'Dein Start:',
    ssProofEyebrow: 'Begründung',
    smEyebrow: 'Verzeichnis',
    smH: 'M³ System-Sitemap',
    smLead: 'Alle Säulen, Module und Eingänge – ohne Umwege.',
    smHome: 'Startseite',
    smFaq: 'FAQ',
    blog: 'Journal',
    blogEyebrow: 'Journal',
    blogH: 'Aus dem System.',
    blogLead: 'Neun Texte. Drei Säulen. Kein Magazin — warum M³ in dieser Reihenfolge arbeitet.',
    blogAll: 'Alle Texte',
    blogRead: 'Lesen →',
    blogMin: 'Min.',
    blogPillar: 'Zur Säule',
    blogRelated: 'Weitere Texte zu dieser Säule',
    blogMore: 'Mehr aus dem Journal',
    contactEyebrow: 'Kontakt',
    contactH: 'Erstgespräch mit Michél.',
    contactLead:
      '20 Minuten. Einordnung, Priorität, nächster Schritt. Unverbindlich — per WhatsApp, Telefon oder Video.',
    contactHow: 'So läuft es ab.',
    contactS1T: 'Nachricht',
    contactS1: 'Du schreibst kurz, wo es gerade hakt. Kein Formular. Kein Fragebogen vorab.',
    contactS2T: 'Gespräch',
    contactS2: 'Wir prüfen ehrlich, ob M³ der richtige Hebel ist. Danach eine erste Einschätzung.',
    contactS3T: 'Nächster Schritt',
    contactS3: 'System Start oder das passende Modul. Du entscheidest. Kein Druck.',
    contactPhone: 'Telefon',
    contactIg: 'Instagram',
    contactWa: 'WhatsApp öffnen',
    catalogEyebrow: 'Katalog',
    catalogH: 'Alle Module. Eine Übersicht.',
    catalogLead:
      'Sieben Bausteine unter M¹ und M². M³ ist der Halt des Systems — kein separates Angebot.',
    catalogWa: 'WhatsApp-Katalog',
  },
  en: {
    writeMe: 'Write me',
    firstTalk: 'Intro call',
    systemStart: 'System Start',
    details: 'Details',
    detailsArrow: 'Details →',
    detailsView: 'View details →',
    whatsapp: 'WhatsApp',
    moreAbout: 'More about Michél',
    openPillar: 'Open pillar →',
    openPillarBtn: 'Open pillar',
    checkStart: 'Check without commitment',
    prevOffer: 'Previous offer',
    nextOffer: 'Next offer',
    startFocus: 'Starting focus:',
    theme: 'Color scheme',
    day: 'Day',
    night: 'Night',
    system: 'System',
    footerLine: 'Performance starts with health.',
    footerAbout:
      'M³ unites metabolism (M¹), biomechanics (M²) and mindset (M³) into a system that fits real life.',
    footerModules: 'Modules',
    footerContact: 'Contact',
    footerWaTalk: 'WhatsApp intro call',
    footerWaCat: 'WhatsApp catalog',
    footerAboutMichel: 'About Michél',
    footerCopy: '© 2026 Michél Meier · M³ Performance & Health',
    imprint: 'Imprint',
    privacy: 'Privacy',
    painfree: 'Pain-free',
    sitemap: 'Sitemap',
    footerMental: 'M³ Mental',
    problemAlt: 'Michél at work in the M³ offers',
    h1a: 'Performance',
    h1b: 'starts with',
    h1c: 'Health.',
    heroPitch:
      'Harder training does nothing if the foundation is on fire. This site is about metabolism, movement and routines — in the right order, with Michél.',
    startEyebrow: 'M³ System Start',
    startH: 'Not just another offer. Your front door.',
    startLead:
      'System Start places you inside this system. You do not need to know the pillar first.',
    moreLearn: 'Learn more',
    lessLearn: 'Less',
    compassH: 'System compass',
    compassP: 'Where do you feel the biggest hurdle right now?',
    frameworkEyebrow: 'M³ System',
    frameworkH: 'How Michél works.',
    frameworkLead: 'Three pillars. A fixed order. Not a catalog of offers.',
    pillarsEyebrow: 'Three pillars. One system.',
    pillarsH: 'Health is not an isolated muscle.',
    pillarsLead: 'Metabolism, movement and mental routines condition each other.',
    modulesEyebrow: 'Offers by pillar',
    modulesH: 'Your options with M³',
    modulesLead:
      'First M¹ Metabolism, then M² Movement. M³ Mental supports both — not a separate paid offer.',
    modulesM3Note:
      'M³ is the closing pillar: sleep, stress and routines — so you continue on your own once the accompanied phase ends. Not an extra offer. The hold when Michél is no longer beside you.',
    modulesM3Cta: 'To pillar M³',
    back: 'Back',
    backHome: 'To homepage',
    michelEyebrow: 'Authenticity',
    michelH: 'Behind M³ there is more than training.',
    michelLead:
      'Michél is not a trainer selling a system off the shelf. He comes from 30+ years of movement and experience: breakdance, the stage, a world title — and from the life in between. Single father. A cervical disc herniation that nearly stopped him. Years when discipline alone was no longer enough.',
    michelLead2:
      'That is why M³ fits. He knows the moment when the body will not follow, even though the head wants it. And he knows the other one: when someone needs understanding — and when they need a clear push. No dogma. No show. With the goal that you eventually continue without him.',
    michelQuote: 'Sometimes you need understanding. Sometimes a kick. Often both.',
    michelMeta: '2006 / 2007 · IDO World Champion · Master Personal Trainer in training · 30+ years of movement',
    faqEyebrow: 'Clarity first',
    faqH: 'Common questions',
    ctaBefore: 'Ready to restructure your ',
    ctaGold: 'health',
    ctaAfter: '?',
    ctaLead: 'Change starts with a decision. 20 minutes of orientation — directly with Michél.',
    ctaTalk: 'Free intro call',
    ctaMoreStart: 'More about System Start',
    forWhom: 'Who it is for',
    forWhomH: 'If this lands, the module lands.',
    includes: 'Included',
    includesH: 'What we actually do.',
    audienceEyebrow: 'Who M³ is for',
    audienceH: 'Real results for real people',
    audienceLead:
      'No miracle pills, no 14-day crash diets. We stay with you until you steer your body yourself.',
    processEyebrow: 'Process',
    processH: 'How we work together',
    preferStart: 'Prefer System Start',
    context: 'Context',
    partOf: 'Part of',
    more: 'Next',
    related: 'Matching modules',
    scienceEyebrow: 'Foundation',
    scienceH: 'What we put underneath.',
    experienceEyebrow: 'Experience',
    principlesEyebrow: 'Method',
    principlesH: 'How we put this into practice.',
    signalsEyebrow: 'Read',
    signalsH: 'When this pillar comes first.',
    pillarCtaLead: '20 minutes. Orientation, priority, next step.',
    noModules: 'M³ is the hold of the system — not a separate offer. Entry runs through System Start.',
    aboutPortrait: 'Michél Meier — founder & personal trainer',
    aboutYears: '30+ years of movement & performance',
    aboutValues: 'Values & stance',
    ssEyebrow: 'M³ System Start',
    ssH: 'Not just another offer. Your front door.',
    ssLead:
      'System Start places you inside this system. You do not need to know the pillar first.',
    ssWhy: 'Why that is true.',
    ssP1:
      'Many want change and do not know where to begin. Do you need nutrition, metabolism, movement — or a combination?',
    ssP2: 'That is what System Start answers: status quo, priorities, a clear next step.',
    ssCompass: 'Where is your biggest hurdle?',
    ssYourStart: 'Your start:',
    ssProofEyebrow: 'The case',
    smEyebrow: 'Directory',
    smH: 'M³ system sitemap',
    smLead: 'Every pillar, module and entrance — without detours.',
    smHome: 'Home',
    smFaq: 'FAQ',
    blog: 'Journal',
    blogEyebrow: 'Journal',
    blogH: 'From the system.',
    blogLead: 'Nine texts. Three pillars. Not a magazine — why M³ works in this order.',
    blogAll: 'All texts',
    blogRead: 'Read →',
    blogMin: 'min',
    blogPillar: 'To the pillar',
    blogRelated: 'More texts on this pillar',
    blogMore: 'More from the journal',
    contactEyebrow: 'Contact',
    contactH: 'Intro call with Michél.',
    contactLead:
      '20 minutes. Orientation, priority, next step. No commitment — via WhatsApp, phone or video.',
    contactHow: 'How it works.',
    contactS1T: 'Message',
    contactS1: 'You write briefly where it is stuck. No form. No questionnaire in advance.',
    contactS2T: 'Call',
    contactS2: 'We check honestly whether M³ is the right lever. Then a first read.',
    contactS3T: 'Next step',
    contactS3: 'System Start or the matching module. You decide. No pressure.',
    contactPhone: 'Phone',
    contactIg: 'Instagram',
    contactWa: 'Open WhatsApp',
    catalogEyebrow: 'Catalog',
    catalogH: 'Every module. One overview.',
    catalogLead:
      'Seven building blocks under M¹ and M². M³ is the hold of the system — not a separate offer.',
    catalogWa: 'WhatsApp catalog',
  },
} as const

export type Ui = (typeof ui)[Lang]

export function useUi(): Ui {
  const { lang } = useLocale()
  return ui[lang]
}
